### ISSUE TITLE
Yammer support

### ISSUE THREAD

**Issue by johan-smits** [gavinkflam/bootstrap-social-rails#4]
Hi,

Can you add Yammer support:
```css
.btn-yammer{color:#fff;background-color:#396b9a;border-color:rgba(0,0,0,0.2)}.btn-yammer:focus,.btn-yammer.focus{color:#fff;background-color:#264f8c;border-color:rgba(0,0,0,0.2)}
.btn-yammer:hover{color:#fff;background-color:#264f8c;border-color:rgba(0,0,0,0.2)}
.btn-yammer:active,.btn-yammer.active,.open>.dropdown-toggle.btn-yammer{color:#fff;background-color:#264f8c;border-color:rgba(0,0,0,0.2)}.btn-yammer:active:hover,.btn-yammer.active:hover,.open>.dropdown-toggle.btn-yammer:hover,.btn-yammer:active:focus,.btn-yammer.active:focus,.open>.dropdown-toggle.btn-yammer:focus,.btn-yammer:active.focus,.btn-yammer.active.focus,.open>.dropdown-toggle.btn-yammer.focus{color:#fff;background-color:#1583d7;border-color:rgba(0,0,0,0.2)}
.btn-yammer:active,.btn-yammer.active,.open>.dropdown-toggle.btn-yammer{background-image:none}
.btn-yammer.disabled,.btn-yammer[disabled],fieldset[disabled] .btn-yammer,.btn-yammer.disabled:hover,.btn-yammer[disabled]:hover,fieldset[disabled] .btn-yammer:hover,.btn-yammer.disabled:focus,.btn-yammer[disabled]:focus,fieldset[disabled] .btn-yammer:focus,.btn-yammer.disabled.focus,.btn-yammer[disabled].focus,fieldset[disabled] .btn-yammer.focus,.btn-yammer.disabled:active,.btn-yammer[disabled]:active,fieldset[disabled] .btn-yammer:active,.btn-yammer.disabled.active,.btn-yammer[disabled].active,fieldset[disabled] .btn-yammer.active{background-color:#396b9a;border-color:rgba(0,0,0,0.2)}
.btn-yammer .badge{color:#396b9a;background-color:#fff}

```
